### PR TITLE
Australian modification of the Charlson index (New API)

### PR DESCRIPTION
**Pull request by torema-ed**
I had a real busy weekend last week so I'm very sorry for the delay.

Would it be fine to add my colleague @SY-CHIA and myself as contributors for this PR?

### CODE REVIEW

**Comment by torema-ed** [comment]
Would it be a good idea to arrange the references by year published in comorbidity.R?

**Comment by ellessenne** [comment]
Hi and thanks for the updated PR! 
Of course, please add your colleague as a contributor to the DESCRIPTION file.
I'll review this as soon as I have the chance in the next few days and then merge.
Thanks again,

Alessandro

**Review by ellessenne — APPROVED** [review]

**Comment by ellessenne** [comment]
Thanks @torema-ed, now merged!

**Comment by torema-ed** [comment]
Thank you for helping me to fix my careless mistakes!

**Pull request merged**
