### PR TITLE
Revised weights for Charlson score

### PR DESCRIPTION
**Pull request by torema-ed**
Hi @ellessenne, I've added in a new choice for `code` in `comorbidity()` to accommodate the revised Charlson weights as mentioned in #17. As mentioned in  #36, this was taken from a script written by @SY-CHIA based on this package.

I will push further changes when you are done re-factoring the API.

### CODE REVIEW

**Comment by axjadamson** [comment]
Came here thinking about updating the weights - so happy to see that someone else has already done it! Just commenting to say that I think this is a very useful update and most people nowadays would prefer to use the Quan et al (2011) updated weights

**Comment by ellessenne** [comment]
Thanks guys, as I said before, I really appreciate it. I am working on it 😃

**Comment by axjadamson** [comment]
> Hi @ellessenne, I've added in a new choice for `code` in `comorbidity()` to accommodate the revised Charlson weights as mentioned in #17. As mentioned in #36, this was taken from a script written by @SY-CHIA based on this package.
> 
> I will push further changes when you are done re-factoring the API.

@torema-ed Great work on the updated weights! Do you have a working version of this you wouldn't mind please sending me just as a stop gap until the pull request is accepted?

**Comment by torema-ed** [comment]
> 
> 
> > Hi @ellessenne, I've added in a new choice for `code` in `comorbidity()` to accommodate the revised Charlson weights as mentioned in #17. As mentioned in #36, this was taken from a script written by @SY-CHIA based on this package.
> > I will push further changes when you are done re-factoring the API.
> 
> @torema-ed Great work on the updated weights! Do you have a working version of this you wouldn't mind please sending me just as a stop gap until the pull request is accepted?

Hi @axjadamson, the forked branch will be up until the pull request is accepted. You can try installing it using `remotes::install_github("torema-ed/comorbidity/", "charlson_update")`.

**Comment by axjadamson** [comment]
> > > Hi @ellessenne, I've added in a new choice for `code` in `comorbidity()` to accommodate the revised Charlson weights as mentioned in #17. As mentioned in #36, this was taken from a script written by @SY-CHIA based on this package.
> > > I will push further changes when you are done re-factoring the API.
> > 
> > 
> > @torema-ed Great work on the updated weights! Do you have a working version of this you wouldn't mind please sending me just as a stop gap until the pull request is accepted?
> 
> Hi @axjadamson, the forked branch will be up until the pull request is accepted. You can try installing it with `remotes::install_github("torema-ed/comorbidity/", "charlson_update")`.

@torema-ed Thanks a lot!

**Comment by ellessenne** [comment]
Hi @torema-ed, I am closing this as the updated weights are implemented in the API refactoring PR that was recently merged (#38, see the `data-raw/make_weights.R` file for details). Please let me know if you spot any mistake there, please!

**Pull request closed without merging**
