### PR TITLE
Add chronic condition "U" codes to ICD-10-AM

### PR DESCRIPTION
**Pull request by DesiQuintans**
In 2015, chronic condition "U" codes were introduced for use in Australian hospital data. The Australian Institute of Health and Welfare says that using these codes as part of case definitions "increases the capture of some chronic conditions up to 15-fold" [^1]. From my experience, adding the U-code for obesity (`U78.1`) improves capture of obesity 14-fold over only using regular ICD-10-AM codes, for example.

This pull request adds these U-codes to the `charlson_icd10_am` mapping. 

The source of the codes was the AIHW's *Data table: Supplementary codes for chronic conditions – evaluation report for population health monitoring* [^1] . U-codes were added to the map if the already-mapped ICD codes were mentioned in the column "ICD–10–AM Diagnosis codes directly mapped".

I **do not** add two specific U-codes to the definition for Chronic Obstructive Pulmonary Disease because their descriptions say they should not be included:

- U83.1 ("Emphysema, without mention of chronic obstructive pulmonary disease")
- U83.3 ("Asthma, without mention of chronic obstructive pulmonary disease")

I re-arranged the codes alphabetically to make comparing them against the table easier. I also de-duplicated one code (J44) in `.maps[[charlson_icd10_am]][["cpd"]]`.

[^1]: https://www.aihw.gov.au/reports/chronic-disease/supplementary-codes-for-chronic-conditions/summary

### CODE REVIEW

**Comment by ellessenne** [comment]
Hi @DesiQuintans, thanks for your PR! 

I am not really keen to deviate from published scores with "ad-hoc" adjustments, as I believe this package should mainly implement published scores/algorithms that have been validated by the authors (in some sense).

For this specific adjustment, I would actually suggest creating a secondary mapping (we could name it `charlson_icd10_am_aihw`, or something like that) to preserve both versions. What do you think about this?

**Comment by DesiQuintans** [comment]
Hi yes, that sounds reasonable and makes sense. I can make such changes in a day or two.

**Comment by ellessenne** [comment]
Sounds good, thanks – and no rush, don't worry!

**Comment by DesiQuintans** [comment]
Okiedokes, I've created a new map called `charlson_icd10_am_ucodes` (calling it `aihw` would make it sound more official than it really is). I also kept the J44 de-duplication for the regular ICD-10-AM map.

**Comment by ellessenne** [comment]
Thanks, looks good!

**Comment by ellessenne** [comment]
Hi @DesiQuintans, I am eager to release a new version of {comorbidity} before CRAN stops for summer (August 1st-16th). Could you kindly confirm whether it's okay to add you as a contributor to the package?

**Comment by DesiQuintans** [comment]
Yes, please do :)

**Comment by ellessenne** [comment]
Awesome, thanks for your contribution! 😄

**Pull request merged**
