### PR TITLE
Add support for latest AHRQ Elixhauser comorbidity calculation

### PR DESCRIPTION
**Pull request by fiksdala**
Hi @ellessenne , 

My colleague @salmasian has mentioned this work to you previously, but this PR aims to address Issue #28 and replicates the AHRQ SAS program (version 3.7) functionality. This required changes to comorbidity.R as well as some other supporting scripts. Of particular note, ICD-10 ranks and DRG codes must be passed to comorbidity() to replicate the AHRQ SAS program. While my fork is 100% functional, some changes to this PR may be required for better integration with the parent repo. Please let me know if there's anything I can do to facilitate those efforts or if you have any other questions. 

Kind regards,
Alex Fiksdal

### CODE REVIEW

**Comment by ellessenne** [comment]
Hi!
Thanks for your PR @fiksdala (and cc @salmasian).
I will need some time to review it (and time has been extremely limited this summer, on top of everything else going on).
I have a list of additions and changes to the `comorbidity` package that are in the pipeline, hopefully it'll be easier in the coming months. I'll get back to you soon!

**Comment by ellessenne** [comment]
I think implementing #35 will greatly simplify implementing scores with DRG codes. 
I am thinking about the API at the moment, and I am considering splitting the _comorbidity mapping_ and the _scoring_ parts into two separate functions, e.g. (in pseudo-code):

```
# function to get comorbidity domains:
comorbidity_matrix = comorbidity(data, type = 'elixhauser', ...)

# function to obtain comorbidity scores, summarising the domains calculated above:
score(comorbidity_matrix, type = 'ahrq', ...)
```

What do you think @salmasian and @fiksdala?

**Comment by fiksdala** [comment]
Thanks @ellessenne for this update! I think that would make sense both from an end-user perspective and in light of recent AHRQ updates to Elixhauser. The SAS program provided by AHRQ only returns the domains (plus some generic summary stats in a separate procedure), and my most recent work (i.e. the 2021 update, not yet finalized) also only returns the comorbidity domains anyway. That decision was made both to more closely replicate the SAS output and because the 2021 AHRQ update includes new comorbidity categories that are incompatible with the scoring schemes used previously.

**Comment by ellessenne** [comment]
Sounds good, thanks. I will work on the API on a separate branch, I'll let you know once ready to test!

**Comment by ellessenne** [comment]
Hi @fiksdala, I am preparing a new release of {comorbidity} for CRAN with the new API (see #43). Once that is done, it will be easier to work on the AHRQ version of the Elixhauser score. Thank you again for your patience!

**Comment by fiksdala** [comment]
Thanks for the update! I've been doing some preliminary work to adapt my
code to your updated API as well, and will dive into that more once your
new release is ready. I'll be sure to reach out down the line when my fok
is close to being ready for a PR.

Thanks,
Alex

**Comment by ellessenne** [comment]
Given the new PR in #52, do you think it would be okay to close this @fiksdala?

**Comment by fiksdala** [comment]
I had forgotten that we had actually submitted this older PR. Yes, we can
close this one and focus on #52 instead. Thanks! -Alex

**Pull request closed without merging**
