### PR TITLE
Add support for ICD-9 code (Charlson)

### PR DESCRIPTION
**Pull request by salmasian**
This is an initial step towards supporting ICD-9. Eventually, I will also add Elixhauser support.

### CODE REVIEW

**Comment by salmasian** [comment]
@ellessenne do no approve this pull request. It is only for you to test and to confirm I am going in the right direction.

I will add support for Elixhauser too, then finalize it for you to approve.

**Comment by ellessenne** [comment]
Hello @salmasian, thanks for the pull request - it looks good. If you can add the coding for the Elixhauser score then I can merge it. I think we should include both the Elixhauser algorithm from the Quan et al. paper and the AHRQ version, what do you think?

**Comment by salmasian** [comment]
I think including only one version of Elixhauser would be enough. Here is a complete patch.

**Comment by ellessenne** [comment]
Thank you @salmasian! I will check and merge later today. 
Is the Elixhauser score based on the AHRQ paper [(here)](https://doi.org/10.1097/MLR.0000000000000735)? I need to add it as a reference before uploading to CRAN a new version.

**Pull request merged**
